#!/bin/bash

export GIT_COMMIT=$(git rev-list -1 HEAD) && \

cd $GITHUB_WORKSPACE/main && \
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a -ldflags "-X main.OECCommitVersion=$GIT_COMMIT
-X main.OECVersion=$OEC_VERSION" -o $GITHUB_WORKSPACE/oec-packages-linux/OpsgenieEdgeConnector main.go && \

cd $GITHUB_WORKSPACE/oec-packages-linux && \
zip -r oec-linux-amd64.zip ./
